//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDNK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKy_DiemDanh
    {
        public string MaDangKy { get; set; }
        public string MaSuKien { get; set; }
        public string MaNguoiDung { get; set; }
        public System.DateTime ThoiGianDangKy { get; set; }
        public string MaTTDK { get; set; }
        public Nullable<System.DateTime> ThoiGianDiemDanh { get; set; }
        public string MinhChung { get; set; }
        public string MaTTDD { get; set; }
        public string NguoiDuyet { get; set; }
        public Nullable<System.DateTime> ThoiGianDuyet { get; set; }
        public string GhiChu { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual SuKien SuKien { get; set; }
        public virtual TrangThaiDangKy TrangThaiDangKy { get; set; }
        public virtual TrangThaiDiemDanh TrangThaiDiemDanh { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
