//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDNK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMucDiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMucDiem()
        {
            this.DanhMucDiem1 = new HashSet<DanhMucDiem>();
            this.MucDiemRenLuyens = new HashSet<MucDiemRenLuyen>();
        }
    
        public string MaDanhMuc { get; set; }
        public string TenDanhMuc { get; set; }
        public int DiemToiDa { get; set; }
        public string MaDanhMucCha { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMucDiem> DanhMucDiem1 { get; set; }
        public virtual DanhMucDiem DanhMucDiem2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MucDiemRenLuyen> MucDiemRenLuyens { get; set; }
    }
}
