//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDNK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKyHeThong
    {
        public string MaNhatKy { get; set; }
        public string MaNguoiDung { get; set; }
        public string ChiTiet { get; set; }
        public System.DateTime ThoiGian { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
