//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDNK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLy_HDNKEntities : DbContext
    {
        public QuanLy_HDNKEntities()
            : base("name=QuanLy_HDNKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DangKy_DiemDanh> DangKy_DiemDanh { get; set; }
        public virtual DbSet<DanhMucDiem> DanhMucDiems { get; set; }
        public virtual DbSet<HocKy> HocKies { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<LopHoc> LopHocs { get; set; }
        public virtual DbSet<MucDiemRenLuyen> MucDiemRenLuyens { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NhatKyHeThong> NhatKyHeThongs { get; set; }
        public virtual DbSet<QuyenHan> QuyenHans { get; set; }
        public virtual DbSet<SuKien> SuKiens { get; set; }
        public virtual DbSet<ThamSoQuyDinh> ThamSoQuyDinhs { get; set; }
        public virtual DbSet<TrangThaiDangKy> TrangThaiDangKies { get; set; }
        public virtual DbSet<TrangThaiDiemDanh> TrangThaiDiemDanhs { get; set; }
        public virtual DbSet<TrangThaiSuKien> TrangThaiSuKiens { get; set; }
        public virtual DbSet<ThongBao> ThongBaos { get; set; }
        public virtual DbSet<NamHoc> NamHocs { get; set; }
    }
}
