//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDNK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuKien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SuKien()
        {
            this.DangKy_DiemDanh = new HashSet<DangKy_DiemDanh>();
            this.SuKien1 = new HashSet<SuKien>();
        }
    
        public string MaSuKien { get; set; }
        public string TenSuKien { get; set; }
        public string Noidung { get; set; }
        public System.DateTime ThoiGianBatDau { get; set; }
        public System.DateTime ThoiGianKetThuc { get; set; }
        public string MaHocKy { get; set; }
        public string MaNamHoc { get; set; }
        public string DiaDiem { get; set; }
        public Nullable<int> SoLuongToiDa { get; set; }
        public string MaMucDRL { get; set; }
        public string CapToChuc { get; set; }
        public string MaNguoiTao { get; set; }
        public string MaTTSK { get; set; }
        public string LyDoHuy { get; set; }
        public int SoLuongDaDangKy { get; set; }
        public string MaSuKienCha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DangKy_DiemDanh> DangKy_DiemDanh { get; set; }
        public virtual HocKy HocKy { get; set; }
        public virtual MucDiemRenLuyen MucDiemRenLuyen { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual TrangThaiSuKien TrangThaiSuKien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuKien> SuKien1 { get; set; }
        public virtual SuKien SuKien2 { get; set; }
        public virtual NamHoc NamHoc { get; set; }
    }
}
