//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDNK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamSoQuyDinh
    {
        public string MaTS { get; set; }
        public string TenTS { get; set; }
        public double GiaTri { get; set; }
        public string DonViTinh { get; set; }
        public bool TinhTrang { get; set; }
    }
}
