//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDNK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public string MaThongBao { get; set; }
        public string MaNguoiNhan { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string DuongDan { get; set; }
        public string Loai { get; set; }
        public string MaLienQuan { get; set; }
        public bool DaDoc { get; set; }
        public System.DateTime ThoiGianTao { get; set; }
        public Nullable<System.DateTime> ThoiGianDoc { get; set; }
    }
}
