//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_HDNK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangThaiDangKy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrangThaiDangKy()
        {
            this.DangKy_DiemDanh = new HashSet<DangKy_DiemDanh>();
        }
    
        public string MaTTDK { get; set; }
        public string TenTTDK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DangKy_DiemDanh> DangKy_DiemDanh { get; set; }
    }
}
